version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-LoadTrucker-ms
    environment:
      POSTGRES_DB: LoadTrucker_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harianbu@3
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-LoadTrucker-ms
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo-LoadTrucker-ms
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-hari-ms:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hariharan
      MONGO_INITDB_ROOT_PASSWORD: harianbu
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-LoadTrucker-ms
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hariharan
      ME_CONFIG_MONGODB_ADMINPASSWORD: harianbu
      ME_CONFIG_MONGODB_SERVER: mongo-LoadTrucker-ms
    depends_on:
      - mongodb
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_Track
    ports:
      - "9411:9411"
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_Trucker
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-LoadTrucker-ms
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

  mail-dev:
    container_name: ms-mail-Tracking-dev
    image: maildev/maildev
    ports:
      - "1080:1080" # Web interface
      - "1025:1025" # SMTP service
    networks:
      - spring-LoadTrucker-ms-net
    restart: unless-stopped

networks:
  spring-LoadTrucker-ms-net:
    driver: bridge

volumes:
  mongo-data-hari-ms:
  postgres-data:
  pgadmin-data:
